[project]
name = "docs"
version = "0.1.0"
description = "Documentation project"
requires-python = ">=3.9"
dependencies = [
    "mkdocs==1.3.0",
    "mkdocs-material==8.3.3",
    "mkdocs-click==0.7.0",
    "mkdocs-video==1.3.0",
]
